
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "build test start"
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - run: yarn test
      - run: yarn build

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
      # - deploy-stage:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: main